# Site settings
title: Cláudio Bichuetti
description: 'Business Card Page'
url: 'https://claudio.network'
baseurl: ''
profilepic: '/images/cb.jpg'
bkimage: '/images/art.jpg'
#  google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Cláudio Bichuetti'
  email: me@claudio.network
  twitter_username: clmbtti
#  facebook_username: clmbtti
  github_username:  clmbtti
  linkedin_username:  bichuetti
#  meetup_name: clmbtti

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
